# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
on:
  push: {}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ^16
      - run: npm install
      - run: npm run check-format
      - run: npm run check-lint
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        neovim_version: ["0.7.2", nightly]
        vscode_version: ["1.69.0", stable]
    runs-on: ${{ matrix.os }}
    needs: [check]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ^16
      - name: "Setup neovim"
        id: "nvim"
        uses: "thinca/action-setup-vim@v1"
        with:
          vim_version: "${{ matrix.neovim_version }}"
          vim_type: "neovim"
          download: always
      - run: npm install
      - run: echo TEST_VSCODE_VERSION="${{ matrix.vscode_version }}" >> $GITHUB_ENV
      - run: echo TEST_NEOVIM_PATH="${{ steps.nvim.outputs.executable_path }}" >> $GITHUB_ENV
      - name: Run tests
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: "npm test"
